### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by kleerkoat** [afj176/rss-ticker#15]
1. Getting this error when starting up and it also seems to correspond with the value set in the "Refresh settings". When I set the value to '1' it pops the error up every minute. Also the feed is not updating.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [rss-ticker](https://github.com/afj176/rss-ticker) package, v5.0.0
### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/rgilmore/.atom/packages/rss-ticker/lib/ticker.coffee:56

TypeError: Cannot read property '0' of null
    at Object.Ticker.init (/Users/rgilmore/.atom/packages/rss-ticker/lib/ticker.coffee:56:42)
    at Object.module.exports.Ticker.Ticker (/Users/rgilmore/.atom/packages/rss-ticker/lib/ticker.coffee:47:4)
    at HTMLUListElement.<anonymous> (/Users/rgilmore/.atom/packages/rss-ticker/lib/rss-ticker-view.coffee:18:36)
    at Function.jQuery.extend.each (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/jquery/dist/jquery.js:374:23)
    at jQuery.fn.jQuery.each (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/jquery/dist/jquery.js:139:17)
    at $.fn.(anonymous function) [as newsTicker] (/Users/rgilmore/.atom/packages/rss-ticker/lib/rss-ticker-view.coffee:13:4)
    at /Users/rgilmore/.atom/packages/rss-ticker/lib/rss-ticker-view.coffee:93:15
    at /Users/rgilmore/.atom/packages/rss-ticker/lib/rss-ticker-view.coffee:107:13
    at FeedParser.parser.onend (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/feed-read/index.js:173:5)
    at Object.FeedParser.parser.onend (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/feed-read/index.js:220:41)
    at emit (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/sax/lib/sax.js:322:33)
    at end (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/sax/lib/sax.js:358:3)
    at Object.write (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/sax/lib/sax.js:588:30)
    at Object.SAXParser.close (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/sax/lib/sax.js:136:38)
    at FeedParser.write (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/feed-read/index.js:228:28)
    at Function.FeedRead.rss (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/feed-read/index.js:191:10)
    at Function.FeedRead.rss (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/feed-read/index.js:148:34)
    at Request._callback (/Users/rgilmore/.atom/packages/rss-ticker/lib/rss-ticker-view.coffee:102:11)
    at Request.self.callback (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/request/request.js:187:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/request/request.js:1048:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/rgilmore/.atom/packages/rss-ticker/node_modules/request/request.js:969:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by afj176** [comment]
Hi @kleerkoat , I will look into this soon(today).

**Comment by chris-zh** [comment]
So is this issue fixed or not?

**Comment by chrismatthieu** [comment]
Just installed rss-ticker and looks like this issue is still an issue.

**Comment by afj176** [comment]
fixed with latest version.
