### ISSUE TITLE
Uncaught Error: Body is not RSS or ATOM

### ISSUE THREAD

**Issue by SoftCreatR** [afj176/rss-ticker#3]
Error: Body is not RSS or ATOM
	  at Request._callback (C:\Users\SoftCreatR\.atom\packages\rss-ticker\node_modules\feed-read\index.js:70:23)
	  at Request.self.callback (C:\Users\SoftCreatR\AppData\Local\atom\app-0.182.0\resources\app\node_modules\request\request.js:123:22)
	  at Request.emit (events.js:119:17)
	  at Request.<anonymous> (C:\Users\SoftCreatR\AppData\Local\atom\app-0.182.0\resources\app\node_modules\request\request.js:1047:14)
	  at Request.emit (events.js:138:20)
	  at IncomingMessage.<anonymous> (C:\Users\SoftCreatR\AppData\Local\atom\app-0.182.0\resources\app\node_modules\request\request.js:998:12)
	  at IncomingMessage.emit (events.js:138:20)
	  at _stream_readable.js:909:16
	  at process._tickCallback (node.js:364:11)

The feed url is: https://community.woltlab.com/board-feed/

**Comment by afj176** [comment]
I am looking into this now, thanks.

**Comment by afj176** [comment]
I have fixed this, now will work with https rss feeds
